import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "@/comp/style/common.scss";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        <main>
          <header>
            <h1>song</h1>
            <nav>
              <Link href="/">Note</Link>
              <Link href="/todo">TodoList</Link>
            </nav>
          </header>
          {children}
          <footer>풋터</footer>
        </main>
        </body>
    </html>
  );
}
